os:
  root: example_value

bot:
  token: your_token_here
  api_url: https://example.com/path

owners:
  - username: example_value
    chat_id: 12345
    cwd: example_value
  - username: example_value
    chat_id: 12345
    cwd: example_value
  
  